### PR TITLE
Generate STM32 devices

### PR DESCRIPTION
**Pull request by ouabache**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hmm, I'm not sure if we should add literally thousands of unverified ICs imported from some data source that we haven't fully verified. Are we even allowed to import KiCAD parts into LibrePCB? What is their license?

Note that all official LibrePCB libraries are CC0 / Public Domain. If KiCAD libraries require attribution (e.g. CC-BY), we cannot use them. The reason is that we don't want to restrict the use of LibrePCB libraries in any way.

@ouabache Maybe it would be best if you could create and maintain a library under your own account (e.g. at https://github.com/ouabache/KiCAD-STMicroelectronics.lplib) for now. Users could still use it to create projects. Over time, if the generated parts prove to be reliable, we can still think about moving them to the standard library. We could also maintain an "official list of user-maintained libraries", where we could list yours, for easier discovery.

**Comment by ouabache** [comment]
Danilo,

Here is the kicad license ( CC-BY-SA 4.0). It lets us redistribute derived
works as long as we include this license. KIcad went to great trouble to
assure its commercial users that they could use kicad without exposing
their works to legal requirements.

Your concern about accuracy is correct. I have found cases where the kicad
pin names differ from the manufacturers data sheet. I think that we could
still offer these as kicad versions without making any claims about
correctness.

I have another github repo named LibrePCB_FPGA_Lattice_iCE40.lplib that I
created from the Lattice datasheets.  That one could be moved to the
librepCB server and offered as part of the library. It was generated by
python scripts that I could provide.

I will also see if I can download the data sheets from STM and generate
their parts. That would be a clean solution.

John Eaton

<https://github.com/ouabache/LibrePCB_FPGA_Lattice_iCE40.lplib>

**Comment by dbrgn** [comment]
> Here is the kicad license ( CC-BY-SA 4.0). It lets us redistribute derived
> works as long as we include this license. KIcad went to great trouble to
> assure its commercial users that they could use kicad without exposing
> their works to legal requirements.

Yes. This means that if you create a commercial project and modify any part of any symbol or package, then those parts must be shared under CC BY-SA as well. Even if you just use parts without modification, they're still copied into your project folder.

It means that if enterprise customers create a project using those parts, then they must ensure that if they relicense or sublicense their project files, they must include exceptions for the KiCAD-converted parts. This is a big hassle for some of the more enterprisey companies, so we try to avoid that for all official libraries.

> I will also see if I can download the data sheets from STM and generate their parts. That would be a clean solution.

I wonder if we could generate schematic symbols from SVD files. @rnestler would that be possible? Do they contain the pinout? That would allow us to create schematic symbols for all ARM based microcontrollers. (SVD licensing is also a tricky topic, btw.)

**Comment by ouabache** [comment]
I did some research. It looks like the kicad library was created using a
tool from gihub.com/Robotips/uConfig to parse the STM datasheets to produce
the kicad symbols. We could do the same thing ourselves and have a database
free from any licensing issues.

I tried compiling the tool but it looks like I need to bump up my QT
install to version 5.2 before it will work

**Comment by dbrgn** [comment]
Interesting! However, parsing PDFs must be very error-prone (I've done some PDF parsing myself in the past). If we need to manually verify every generated part, we don't really save any time versus extracting the information manually.

However, SVD files are machine readable and might contain all information we need: http://www.keil.com/pack/doc/cmsis/svd/html/index.html Debuggers/IDEs use this data to visualize chips, so that might work!

**Comment by ouabache** [comment]
Well I got uConfig to run (The README.md lied about the version) and tried
to read a STM datasheet without success. The website reported an issue with
STM about 3 years ago and it looks like it was never fixed.

I have no ideal how they generated the kicad parts unless they hand edited
every one of them.

**Comment by dbrgn** [comment]
Hmm, I checked and SVD files only contain register definitions, not pinout information.

Anyways, I suspect that if we have a generator, extracting the information from the datasheets manually wouldn't be *that* much work, as long as we pick a storage format that is similar to the way the datasheets are structured. It would take maybe 10 minutes per MCU family?

I also found https://github.com/esden/stm32-pinouts, but I'm not sure how correct, up to date and complete these are.

**Comment by ouabache** [comment]
Success,

ST has a tool called CubeMX that lets you select and configure their entire
microprocessor line.  It dumps out a csv file with pin_number and
pin_name.  I can use this output to create a symbol.

I can create a library part showing all the alternate functions on each pin
and I can also create a symbol showing the exact configuration that the
user selects. We would offer the generic ones on the server but give them
the scripts so that they can create their own custom libraries.

Its a gui tool so I might have to slug through the "select part, save as,
repeat" for their entire line.

**Comment by dbrgn** [comment]
Nice find! I think as long as the CSV file just contains the pin mappings, I don't think there should be any copyright issues.

@ubruhin @rnestler do you agree that using the CubeMX-based CSV files to generate library elements is a feasible approach?

**Comment by ouabache** [comment]
I have a plan for adding the ST 32 bit micros to the LibrePCB library.

The CubeMX tool does have a scripting mode so I have download 1341 parts
into csv files with pin numbers and pin names. I can modify my scripts to
generate a symbol,component and device for each one.

The problem is that there is no information on pin placement or order so
that the symbols will all be boxes with all pins on one side in their pad
order. Not very useful. I also have the symbols that I generated from the
kicad library that I could include as a symbol variant for each component.
This would give us a usable library.

The problem is that the python code in librepcb-parts-generator does not
support symbol variants. I have modified the code in the bga branch of my
fork but merging it will break the other scripts that use it.

Danilo, Can you fix the component.py code to accept multiple variants
instead of only one?

John Eaton

>

**Comment by dbrgn** [comment]
> The CubeMX tool does have a scripting mode so I have download 1341 parts
into csv files with pin numbers and pin names. I can modify my scripts to
generate a symbol,component and device for each one.

Nice! Can we also get alternative functions in a structured form?

> The problem is that there is no information on pin placement or order so
that the symbols will all be boxes with all pins on one side in their pad
order.

I think we could fix that with some own code, since STM pin naming is quite consistent. Maybe you can share an example file?

> Danilo, Can you fix the component.py code to accept multiple variants instead of only one?

The `Component` entity has an `add_variant` method which allows adding additional symbol variants. Does that help?

**Comment by ouabache** [comment]
Here's s sample file that we get. The gui allows you to also dump the alt
functions for each pin but I have not figured out how to switch into that
mode.

We could do a template with a superset of all pin names and delete any that
aren't part of a given chip.

Your add_variant method is hard coded to only one gate. I had to change it
to a list with a add_gate method to allow any number of gates. My code is on
gihub.com/ouabache/librepcb-parts-generator branch bga if you want to look
at it.

Please check it over, I am not an experienced python programmer

**Comment by dbrgn** [comment]
Hm, I cannot see the file. In case you attached it to the e-mail: I think you need to go to the GitHub UI (https://github.com/LibrePCB-Libraries/STMicroelectronics.lplib/pull/3) and drag&drop the file into the comment field.

**Comment by ouabache** [comment]
[STM32WB55CEUx.txt](https://github.com/LibrePCB-Libraries/STMicroelectronics.lplib/files/4135874/STM32WB55CEUx.txt)
 Here is the STM csv file

**Comment by dbrgn** [comment]
That looks great already!

Can we also dump the package variant (e.g. LQFP48) somewhere in that file, e.g. before the CSV header?

Alternative functions would also be great.

I can do a quick draft for code that example file you sent. I'm pretty sure we'll be able to group the signals somehow.

> Your add_variant method is hard coded to only one gate. I had to change it
to a list with a add_gate method to allow any number of gates.

Ahh, I see! Sorry for not looking at your BGA PR yet, it's quite big and I couldn't find time to take a deep look so far.

Yeah, sure, updating the entity code shouldn't be a big problem.

**Comment by ouabache** [comment]
I don't want to touch that file since future updates will require that we
rerun everything.

I can create a second file customized to our needs .

Go ahead and update the code in the master and get your scripts working
then I will adapt get my stuff working with the new master

**Comment by dbrgn** [comment]
Here's a first attempt at a grouping script:

```
<MCU STM32WB55CEUx (48 pins)>
Pin types: {'I/O', 'MonoIO', 'Power', 'Reset', 'NC'}
# I/O
  - PA0 [9]
  - PA1 [10]
  - PA10 [36]
  - PA11 [37]
  - PA12 [38]
  - PA13 [39]
  - PA14 [41]
  - PA15 [42]
  - PA2 [11]
  - PA3 [12]
  - PA4 [13]
  - PA5 [14]
  - PA6 [15]
  - PA7 [16]
  - PA8 [17]
  - PA9 [18]
  - PB0 [28]
  - PB1 [29]
  - PB2 [19]
  - PB3 [43]
  - PB4 [44]
  - PB5 [45]
  - PB6 [46]
  - PB7 [47]
  - PB8 [5]
  - PB9 [6]
  - PC14-OSC32_IN [2]
  - PC15-OSC32_OUT [3]
  - PE4 [30]
  - PH3-BOOT0 [4]
# MonoIO
  - OSC_IN [25]
  - OSC_OUT [24]
  - RF1 [21]
# Power
  - VBAT [1]
  - VDD [20]
  - VDD [35]
  - VDD [48]
  - VDDA [8]
  - VDDRF [23]
  - VDDSMPS [34]
  - VDDUSB [40]
  - VFBSMPS [31]
  - VLXSMPS [33]
  - VSSRF [22]
  - VSSSMPS [32]
# Reset
  - NRST [7]
# NC
  - AT0 [26]
  - AT1 [27]
```

I think with some heuristics, we can work with that. I already have a few ideas on grouping and placement!

If you don't mind, I'll go ahead and will try to generate a symbol for that file. I'd be glad if you could try to clean up and document your approach on how to generate these CSV files :slightly_smiling_face: Maybe for now any required scripts could be placed in a subdirectory called `stm32/`, with the CSV data files in `stm32/data/`. Documentation could go into a markdown file `stm32/README.md`.

**Comment by dbrgn** [comment]
And here's generated grouped deduplicated placement info (Y position followed by name):

```
Placement info:
  Left 16 pins 19 steps
  Right 30 pins 30 steps
  Height: 30 steps, max_y: 15 steps
Placement:
  Left:
    15 NRST
    13 VBAT
    12 VDD
    11 VDDA
    10 VDDRF
    9 VDDSMPS
    8 VDDUSB
    7 VFBSMPS
    6 VLXSMPS
    5 VSSRF
    4 VSSSMPS
    2 OSC_IN
    1 OSC_OUT
    0 RF1
    -2 AT0
    -3 AT1
  Right:
    15 PA0
    14 PA1
    13 PA10
    12 PA11
    11 PA12
    10 PA13
    9 PA14
    8 PA15
    7 PA2
    6 PA3
    5 PA4
    4 PA5
    3 PA6
    2 PA7
    1 PA8
    0 PA9
    -1 PB0
    -2 PB1
    -3 PB2
    -4 PB3
    -5 PB4
    -6 PB5
    -7 PB6
    -8 PB7
    -9 PB8
    -10 PB9
    -11 PC14-OSC32_IN
    -12 PC15-OSC32_OUT
    -13 PE4
    -14 PH3-BOOT0
```

Sort order still needs to be tweaked (PA10 should follow PA9, not PA1) but it's a good start.

**Comment by dbrgn** [comment]
Yeah, the approach works :tada: First generated symbol from that CSV file (not 100% done yet):

2020-01-31-003913_890x906_scrot

I'm gone over the weekend, but I'll try to finish this early next week. @ouabache if you manage to generate more (all?) CSV files by then, maybe we can try a run over all STM32 MCUs.

Components should also be straightforward to generate.

Current code is in the [stm32 branch of parts generator](https://github.com/LibrePCB/librepcb-parts-generator/tree/stm32).

**Comment by ouabache** [comment]
I will push the scripts and csv files that I have been using

**Comment by ouabache** [comment]
I created all the symbols and found 455 of them would not load due to
problems in their signal names. We will  need to detect these names and fix
them. Parsing out anything with space() will get most of them but the - and
/ characters will require a fix to librepcb


[EXCEPTION] File parse error: Invalid identifier: 'PA14 (JTCK/SWCLK)'
[EXCEPTION] File parse error: Invalid identifier: 'PA15 (JTDI)'
[EXCEPTION] File parse error: Invalid identifier: 'PB3 (JTDO/TRACESWO)'
[EXCEPTION] File parse error: Invalid identifier: 'PB4 (NJTRST)'
[EXCEPTION] File parse error: Invalid identifier: 'PC14 - OSC32_IN'
[EXCEPTION] File parse error: Invalid identifier: 'PC14 / OSC32_IN'
[EXCEPTION] File parse error: Invalid identifier: 'PC14-OSC32_IN (OSC32_IN)'
[EXCEPTION] File parse error: Invalid identifier: 'PC14-OSC32_IN (PC14)'
[EXCEPTION] File parse error: Invalid identifier: 'PC15 - OSC32_OUT'
[EXCEPTION] File parse error: Invalid identifier: 'PC15-OSC32_OUT
(OSC32_OUT)'
[EXCEPTION] File parse error: Invalid identifier: 'PC15-OSC32_OUT (PC15)'
[EXCEPTION] File parse error: Invalid identifier: 'PF0 / OSC_IN'
[EXCEPTION] File parse error: Invalid identifier: 'PF1 / OSC_OUT'
[EXCEPTION] File parse error: Invalid identifier: 'PH0 - OSC_IN'
[EXCEPTION] File parse error: Invalid identifier: 'PH3-BOOT0 (BOOT0)'
[EXCEPTION] File parse error: Invalid identifier: 'PI8- ANTI TAMP2'

>

**Comment by dbrgn** [comment]
Closing in favor of #5. Thanks for kicking this off!

**Pull request closed without merging**
