### PR TITLE
Add STM32L071KxTx

### PR DESCRIPTION
**Pull request by dbrgn**
- Digikey: https://www.digikey.ch/product-detail/de/stmicroelectronics/STM32L071KBT6/497-18577-ND/6166986
- Datasheet: https://www.st.com/resource/en/datasheet/stm32l071cb.pdf

img

### CODE REVIEW

**Comment by ubruhin** [comment]
Just one thing: IMHO it looks a bit ugly that at the symbol pin at top right is lower than the top left pin ;)

image

I guess I would prefer to reduce the symbol height by 2.54mm, although then the origin is not in the center of the symbol, but actually that's not a requirement anyway (many symbols are not perfectly centered).

**Comment by dbrgn** [comment]
Uh, that's definitely a mistake, I didn't notice that... Will fix it, I'd also consider it ugly :)

**Comment by dbrgn** [comment]
@ubruhin better? It's still symmetric, I just removed the space between PA and PB pins.

img

**Review by ubruhin — APPROVED** [review]
LGTM :+1:

**Pull request merged**
