### PR TITLE
Add generated STM32 sym/cmp/dev

### PR DESCRIPTION
**Pull request by dbrgn**
This adds symbols and components for *all* STM32 MCUs, as well as devices for all MCUs where we have a matching package. Data source is the STM32CubeMX database, see https://github.com/LibrePCB/stm-db/.

- 286 symbols
- 969 components
- 870 devices

Currently supported packages: LQFP{32,44,48,64,80,100,144,176,208}, SO8[N], TSSOP{14,20}. More devices can be generated once some of the other packages (like BGA) have been added to the base library.

Generated using librepcb-parts-generator (generate_stm_mcu.py) based on the STM32CubeMX database.

https://github.com/LibrePCB/librepcb-parts-generator/pull/80

### CODE REVIEW

**Comment by dbrgn** [comment]
Hm, the non-canonical files (see CI) made me notice that some devices (e.g. `dev/134b487b-670f-4304-ba7c-b748284fe02b/device.lp`) have multiple signals mapped to the same pad. That probably shouldn't happen.

**Comment by dbrgn** [comment]
I picked out a few random devices and verified the pinout against the datasheet:

- STM32L476RETx
- STM32F030CCTx
- STM32F100RCTx
- STM32F051C4Tx
- STM32L052K6Tx
- STM32G041J6Mx
- STM8AF5288Tx

Things I noticed for the STM32G041J6Mx:

- The pin names overlap:

2020-03-06-160448_483x296_scrot

- Some pin names differ between datasheet and symbol:
  - Datasheet: VDD/VDDA, LibrePCB/CubeMX: VBAT
    - It's a bit strange since the actual VBAT pin is only available in the LQFP48 version... But it matches CubeMX.
  - Datasheet: NRST/PA0/PA1/PA2/PF2, LibrePCB/CubeMX: NRST/PA0/PA1/PA2 
    - NRST and PF2 are the same thing, so this doesn't matter

  Probably nothing we have to worry about too much.

**Comment by ubruhin** [comment]
Awesome! :tada: :rocket:

> The pin names overlap:
> Some pin names differ between datasheet and symbol:

I see following options to handle them:
- Keep them as-is -> not critical, but somehow not nice to have overlapping texts in the library...
- Blacklist those devices in the generator so they are simply not generated, i.e. the problem could be solved some day later if needed -> my favorite, if blacklisting is easy to implement.
- Make pin names shorter e.g. by replacing "PB7/PB8/PB9" by "PB7..9".

I wonder if it makes sense to generate single symbols for MCUs with > 100 pins (they are *huge*), but since generated symbols are "for free", it shouldn't hurt... :wink:

But my main question: Should we use a pin distance of 5.08mm for all power pins? As far as I can see, in all symbols there is enough space available to increase pin distance without increasing the total symbol size. But especially for power pins it could lead to cleaner schematics if you can connect capacitors (which 5.08mm pin distance) directly to power pins. What do you think @dbrgn?

**Comment by dbrgn** [comment]
> I see following options to handle them

I have another idea: Based on the longest pin name present, we can generate symbols in a "wide" version. That should fix the problem for affected MCUs while keeping most symbols nice and small.

> I wonder if it makes sense to generate single symbols for MCUs with > 100 pins (they are huge), but since generated symbols are "for free", it shouldn't hurt...

Yep, agreed. We can always add split variants later on.

> But my main question: Should we use a pin distance of 5.08mm for all power pins? As far as I can see, in all symbols there is enough space available to increase pin distance without increasing the total symbol size. But especially for power pins it could lead to cleaner schematics if you can connect capacitors (which 5.08mm pin distance) directly to power pins.

Should be doable. It makes the logic a bit more complex, but I don't think it should be too complex.

**Comment by dbrgn** [comment]
The large spacing can look a bit ridiculous though in some cases...



@ubruhin are you sure you want that?

Here's a device with fewer power pins:

**Comment by dbrgn** [comment]
@ubruhin ping. Would be good if we could land this soon.

**Comment by ubruhin** [comment]
>> I see following options to handle them
>
> I have another idea: Based on the longest pin name present, we can generate symbols in a "wide" version. That should fix the problem for affected MCUs while keeping most symbols nice and small.

Probably requires some effort to implement, but I'd be fine with that solution :+1:

> The large spacing can look a bit ridiculous though in some cases...

Yeah sure that looks a bit strange. But for the symbols with fewer power pins, it looks nice and makes schematic drawing easier. Hard to say which variant would be overall better... What about an ugly condition in the generator like `pin_spacing = 5.08 if len(power_pins) < 9 else 2.54`? :see_no_evil:

**Comment by dbrgn** [comment]
I'll try to finish this today. For the record, remaining open issues:

- [x] Double pin spacing between power pins
- [x] Generate wide symbols if the longest pin name is longer than a certain threshold (test case: STM32G041J6Mx)

> Yeah sure that looks a bit strange. But for the symbols with fewer power pins, it looks nice and makes schematic drawing easier. Hard to say which variant would be overall better... What about an ugly condition in the generator like `pin_spacing = 5.08 if len(power_pins) < 9 else 2.54`? :see_no_evil: 

I decided to always keep the double spacing, since a part with a lot of power pins always has a lot of I/O pins as well, so it should be OK.

**Comment by dbrgn** [comment]
@ubruhin Both issues should be fixed now.

New version of STM32G041J6Mx (the symbol with - by far - the widest signal name):

g041

Signal sort order was previously non-deterministic, I ensured that they are now sorted by name. (It seems that LibrePCB retains sort order when editing.)

**Review by ubruhin — APPROVED** [review]
Awesome, thanks a lot @dbrgn and @ouabache! :tada:

**Review by ubruhin — CHANGES_REQUESTED** [review]
Whoops, I just realized that when I re-generate the library elements on my own, there are several differences compared to the files in this PR :scream: Can you reproduce that, @dbrgn?

**Comment by dbrgn** [comment]
No, I cannot reproduce that. It would help if you would show an example of such a diff :slightly_smiling_face:

**Comment by ubruhin** [comment]
Here the diff generated with the latest version of the `stm-db` repository and the parts generator: https://github.com/LibrePCB-Libraries/STMicroelectronics.lplib/commit/d91d343e12f4eacfdc746b276fbc7566ec641f24

**Comment by dbrgn** [comment]
Huh, thanks for the diff. First of all, it doesn't make sense that the component mentions the package, because the same component can be available in different packages. I assume that due to differences in the Python version, certain collections are sorted in a non-deterministic way (or alternatively a different order is used when parsing the data files in the file system), causing different MCUs to be used when generating the description of the (merged) component. The solution here is to remove the package from the component description.

However, that one change where the number of I/Os is changed, looks alarming. I'll try to figure out why this happens...

**Comment by dbrgn** [comment]
I think I was right with my suspicion above, regarding non-deterministic order. The missing frequency has the same reason, one of the MCU data files is simply missing that information. Solved by removing the variable information from the cmp description.

I also found the reason for the other error, some STM8 MCUs don't follow the naming scheme of the STM32 MCUs, so the grouping into categories was wrong. I tried to find a "system" for a long time, but it would be a huge amount of work to get it fixed properly.

The simplest way for now is to exclude STM8 MCUs from being generated. To fix this, we have two options:

- Add manual rules for every STM8 family/subfamily
- Don't group STM8 MCUs into shared components

But that can be done in the future in a separate PR, should the need for STM8 MCUs arise.

I hope everything else is still correct, after this fix. @ubruhin can you test now whether re-generating the elements results in any changes? Note that all UUIDs are updated (but that should not affect anything).

**Comment by ubruhin** [comment]
OK, thanks for investigating this. I agree on removing STM8 MCUs for now (with a comment in the generator *why* they are not generated yet).

Removing the variable information from the component description is fine for me too. But to be honest, I'd really love to see an assert which checks that the information requested from MCU is identical for *all* grouped components. 

Example:

```python
def get_item(items):
  assert len(set(items)) == 1  # ensure that all items are identical
  return items[0]

...

def generate_cmp(name: str, mcus: list[MCU], ...):  # taking a list of MCU
    (placement, pin_mapping) = get_item([mcu.generate_placement_data(debug) for mcu in mcus])

...

for name, mcus in components.items():
    generate_cmp(name, mcus, symbol_map, debug)  # passing ALL mcus instead of just mcus[0]
```

Something like that would give me a much better feeling about the correctness of the generated library elements :wink:

EDIT: Or much simpler: Just generate the component for *all* MCUs of a group, and check if they are all identical?

**Comment by dbrgn** [comment]
I prefer the first approach, it's easier to implement :) It doesn't work directly the way you suggested (because the tuple isn't hashable), but was easy to modify.

Assertions are added, they seem to pass.

(When I added the assertions I also added a stupid mistake that cost me about 2-3 hours of clueless debugging... I initially forgot to re-define `mcu` in `generate_cmp` which caused the `mcu` variable to be taken from the loop variable in a list comprehension. This caused inconsistencies between name and description of a component. Python variable scoping is weird :roll_eyes:)

**Comment by dbrgn** [comment]
@ubruhin I added your two commits to my generator branch. the generated output is still the same! this should now be ready to merge.

**Review by ubruhin — APPROVED** [review]

**Pull request merged**
